# Generated by Django 3.2.7 on 2021-09-29 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0002_commentbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentbook',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='book_app.book'),
        ),
        migrations.AddField(
            model_name='commentbook',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
